### ISSUE TITLE
I can't connect metamask，how to resolve？

### ISSUE THREAD

**Issue by lrmuyi** [makerdao/mcd-cdp-portal#115]
![image](https://user-images.githubusercontent.com/25303760/65749865-9a529680-e139-11e9-9780-6843c168d362.png)

**Comment by b-pmcg** [comment]
@lrmuyi check the URL, you should see a query parameter like `?network=kovan`, make sure your MetaMask network is also set to Kovan. Currently Kovan is the only supported network as we are still in development.

**Comment by b-pmcg** [comment]
Closing this, @lrmuyi let us know if you have any other problems.
