### ISSUE TITLE
Bug TypeError: Intl.NumberFormat(...).formatToParts(...).find(...) is undefined

### ISSUE THREAD

**Issue by sebamenabar** [makerdao/mcd-cdp-portal#149]
Hi, I'm not familiarized with the code so I'm not sure how to report or debug this, but when I try to manage my vault I get the following error:

`TypeError: Intl.NumberFormat(...).formatToParts(...).find(...) is undefined`

![Captura de pantalla 2019-11-18 a la(s) 16 18 38](https://user-images.githubusercontent.com/13748963/69082567-1a50fa80-0a1f-11ea-8abe-eab7e3d49227.png)

Please let me know if there's something I can do to help.

**Comment by sebamenabar** [comment]
For some reason is working now, I'm gonna leave it open for a little longer just in case...

**Comment by levity** [comment]
We had this report from some other users as well and pushed a fix :)
