### ISSUE TITLE
Display current DSR  on oasis.app/save page (without connected wallet)

### ISSUE THREAD

**Issue by jernejml** [makerdao/mcd-cdp-portal#182]
Novice or potential crypto (without connected metamask or other wallet)  users might land on the oasis landing page or save page.

request:
- display current DSR rate on oasis/save page (without connected wallet)
- display current DSR on the landing page (box Save)

**Comment by michaelelliot** [comment]
The savings rate has been [added](https://github.com/makerdao/mcd-cdp-portal/commit/5cba15faebeb93c5c7a9c66f676d6309877d70a1) to the Oasis Save sidebar and will be in production soon.
