### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by kevholder** [makerdao/mcd-cdp-portal#187]
I'm trying to setup a dev environment and followed instructions in README. Launching http://localhost:3000/save?network=test&simplePriceFeeds=1 works but if I click "Start Trading", I am being redirected to https://oasis.app/trade/ and the other 2 buttons, e.g. http://localhost:3000/borrow?network=test&simplePriceFeeds=1 and http://localhost:3000/save?network=test&simplePriceFeeds=1 give the following error:

```
Unhandled Rejection (Error): Unsupported network: test
_callee$
src/maker.js:24
  21 |   { currency: BAT, ilk: 'BAT-A' }
  22 | ];
  23 | 
> 24 | export async function instantiateMaker({
  25 |   rpcUrl,
  26 |   network,
  27 |   testchainId
```

**Comment by kevholder** [comment]
The URL should be http://localhost:3000?network=testnet&simplePriceFeeds=1 in the README, sent a PR

**Comment by rodrprincipe** [comment]
@kevholder may I ask you how did you set up the dev env? I am getting an error after following the instructions and  connecting to http://localhost:3000?network=testnet&simplePriceFeeds=1
![localhost_3000__network=testnet simplePriceFeeds=1](https://user-images.githubusercontent.com/6618552/138936469-118db67a-79aa-44fd-9f6f-4372883d0aad.png)
