### ISSUE TITLE
Connecting to kovan via metamask isn't working

### ISSUE THREAD

**Issue by JonahGroendal** [makerdao/mcd-cdp-portal#191]
I'm trying to open a CDP on kovan to get some dai to test my contracts with, but when I navigate to oasis.app/borrow and try to connect metamask on kovan I get an alert saying "Error: browser ethereum provider and URL network param do not match.". This only happens when metamask is connected to kovan, if I switch to mainnet it works just fine. It would be really nice to have this working on kovan so there's an easy way for developers to generate testnet DAI.

**Comment by levity** [comment]
The app works with kovan, but you have to add a query parameter to enable it: https://oasis.app/borrow?network=kovan

The app has a read-only mode for viewing information about vaults that you don't own, even without a wallet connected, so we don't just try to figure out the network from the user's wallet.
