### ISSUE TITLE
(Oasis Save UI) Incorrect value and calculation for refreshing the current earnings 

### ISSUE THREAD

**Issue by rootslab** [makerdao/mcd-cdp-portal#199]
https://github.com/makerdao/mcd-cdp-portal/blob/87b0c58c6965a3fd0a7e77a2ec02c761d9354791/src/components/DSRInfo.js#L133

Can you explain the use of this variable? 

**amountChangePerSecond**  = dsr_current_balance * ( curr_dsr_rate_per_sec - 1 )

the correct formula to refresh (compounded yield ) is something like this: 

**init_balance * Math.pow( curr_rate_per_sec , elapsed_secs  )**

we need only the **initial balance**, the **elapsed time**, and the **current rate**, and to maintain a coherent increasing value in time, **we need to use powering not multiplication**.

The current variable doesn't seem to be of any help for this compound calculation.

**Comment by rootslab** [comment]
I post a simple function for reference
```
var refresh_balance = function ( init_balance, rate_per_sec, refresh_ms, init_tstamp, cback ) {
    let now = Date.now
    	, pow = Math.pow 
        , round = Math.round
        // initial balance, default 1
        , balance = init_balance || 1
        // increment rate per second, default apy 8%
        , rate = rate_per_sec || 1.0000000024404185
        // refresh UI every x millis
        , ms = refresh_ms || 50
        // timestamp in millis or simply now
        , start = init_tstamp || now()
        // 1 year is made of 365 days, for me, someone else uses 365.2422
        , secs_1_year = 365 * 86400
        // expected APY with current rate per sec 
        , curr_apy = 100 * ( pow( rate, secs_1_year ) - 1 )
    	// callback or empty function
        , cb = ( typeof cback === 'function' ) ? cback : function () {}
    	;      
    return setInterval( function () {        
    	let secs = ( now() - start ) / 1000
      	     // real balance is compounded every sec
             , extimated = balance * pow( rate , round( secs ) )
             // approximation for refreshing UI
             , updated = balance * pow( rate , secs )
             ;
        // update values executin the callback
        cb( secs, extimated, updated, curr_apy, balance );
     }, ms );
};

```

**Comment by Padraic-O-Mhuiris** [comment]
Thanks for your issue @rootslab. You are correct that it does not compound per interval, only increments per interval. The reasoning for this is is that performance-wise, calculating the power of a number per fractions of a second is very computationally expensive.
This would then lead to a divergence of the value on-chain versus what would be shown in the UI. 

However, the UI will recalculate this `amountChangePerSecond` value for each time the `drip` function is called, which results in the balance being corrected to the value on chain. More simply, what the component is doing is calculating what the interest earned per second after each time drip is called. It then increments on that value until drip is called and it recalculates.

There are issues with the current implementation, we have a change in development to make this more performant and more accurate.

**Comment by javier-tarazaga** [comment]
Yeap @Padraic-O-Mhuiris I was going to mention that atm, the values are not calculated correctly when left the tab open for a while. When you refresh the page, the values tend to reduce in size a bit.

**Comment by Padraic-O-Mhuiris** [comment]
@javier-tarazaga Yes that is a mistake on our end, the fix we have in the develop branch, [here](https://mcd-cdp-portal-git-develop.mkr-js-prod.now.sh/) should be much more accurate. Hopefully, we will have this merged into the main branch shortly
