### ISSUE TITLE
https://mcd-cdp-portal-git-develop.mkr-js-prod.now.sh/borrow?network=kovan crashes

### ISSUE THREAD

**Issue by yaronvel** [makerdao/mcd-cdp-portal#236]
I get this error:
```Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

In addition i get a similar error when i am running the development environment on my local env.

**Comment by levity** [comment]
Fixed now! Sorry about that. @chrisbradbury88 @Padraic-O-Mhuiris @ferni
